
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.text
{
public sealed partial class Text : Luban.BeanBase
{
    public Text(JSONNode _buf) 
    {
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["zh"].IsString) { throw new SerializationException(); }  Zh = _buf["zh"]; }
        { if(!_buf["en"].IsString) { throw new SerializationException(); }  En = _buf["en"]; }
    }

    public static Text DeserializeText(JSONNode _buf)
    {
        return new text.Text(_buf);
    }

    public readonly string Key;
    public readonly string Zh;
    public readonly string En;
   
    public const int __ID__ = -1083776658;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "zh:" + Zh + ","
        + "en:" + En + ","
        + "}";
    }
}
}

