
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.text
{
public partial class TbText
{
    private readonly System.Collections.Generic.Dictionary<string, text.Text> _dataMap;
    private readonly System.Collections.Generic.List<text.Text> _dataList;
    
    public TbText(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, text.Text>(count);
        _dataList = new System.Collections.Generic.List<text.Text>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            text.Text _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::dataTables.text.Text.DeserializeText(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, text.Text> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<text.Text> DataList => _dataList;

    public text.Text GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public text.Text Get(string key) => _dataMap[key];
    public text.Text this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

