
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.test
{
public partial class TbMinimal
{
    private readonly System.Collections.Generic.Dictionary<int, test.Minimal> _dataMap;
    private readonly System.Collections.Generic.List<test.Minimal> _dataList;
    
    public TbMinimal(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, test.Minimal>(count);
        _dataList = new System.Collections.Generic.List<test.Minimal>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            test.Minimal _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.test.Minimal.DeserializeMinimal(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, test.Minimal> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<test.Minimal> DataList => _dataList;

    public test.Minimal GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public test.Minimal Get(int key) => _dataMap[key];
    public test.Minimal this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

