
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.matrix
{ 
    /// <summary>
    /// quality enum
    /// </summary>
    public enum EQuality
    {
        /// <summary>
        /// Common
        /// </summary>
        Common = 1,
        /// <summary>
        /// Rare
        /// </summary>
        Rare = 2,
    }

} 

