
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.matrix
{
public sealed partial class GroupServerBean : Luban.BeanBase
{
    public GroupServerBean(JSONNode _buf) 
    {
        { if(!_buf["v"].IsNumber) { throw new SerializationException(); }  V = _buf["v"]; }
    }

    public static GroupServerBean DeserializeGroupServerBean(JSONNode _buf)
    {
        return new matrix.GroupServerBean(_buf);
    }

    public readonly int V;
   
    public const int __ID__ = 761719077;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "v:" + V + ","
        + "}";
    }
}
}

