
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.matrix
{
public sealed partial class GroupFields : Luban.BeanBase
{
    public GroupFields(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["f_none"].IsNumber) { throw new SerializationException(); }  FNone = _buf["f_none"]; }
        { if(!_buf["f_row_c"].IsNumber) { throw new SerializationException(); }  FRowC = _buf["f_row_c"]; }
        { if(!_buf["f_row_s"].IsNumber) { throw new SerializationException(); }  FRowS = _buf["f_row_s"]; }
        { if(!_buf["f_cell_c"].IsNumber) { throw new SerializationException(); }  FCellC = _buf["f_cell_c"]; }
        { if(!_buf["f_cell_s"].IsNumber) { throw new SerializationException(); }  FCellS = _buf["f_cell_s"]; }
        { if(!_buf["f_conflict"].IsNumber) { throw new SerializationException(); }  FConflict = _buf["f_conflict"]; }
    }

    public static GroupFields DeserializeGroupFields(JSONNode _buf)
    {
        return new matrix.GroupFields(_buf);
    }

    public readonly int Id;
    public readonly int FNone;
    public readonly int FRowC;
    public readonly int FRowS;
    public readonly int FCellC;
    public readonly int FCellS;
    public readonly int FConflict;
   
    public const int __ID__ = -915233973;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "fNone:" + FNone + ","
        + "fRowC:" + FRowC + ","
        + "fRowS:" + FRowS + ","
        + "fCellC:" + FCellC + ","
        + "fCellS:" + FCellS + ","
        + "fConflict:" + FConflict + ","
        + "}";
    }
}
}

