
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.matrix
{
public partial class TbBasic
{
    private readonly System.Collections.Generic.Dictionary<int, matrix.BasicRecord> _dataMap;
    private readonly System.Collections.Generic.List<matrix.BasicRecord> _dataList;
    
    public TbBasic(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, matrix.BasicRecord>(count);
        _dataList = new System.Collections.Generic.List<matrix.BasicRecord>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            matrix.BasicRecord _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.matrix.BasicRecord.DeserializeBasicRecord(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, matrix.BasicRecord> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<matrix.BasicRecord> DataList => _dataList;

    public matrix.BasicRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public matrix.BasicRecord Get(int key) => _dataMap[key];
    public matrix.BasicRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

