
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.matrix
{
public partial class TbContainers
{
    private readonly System.Collections.Generic.Dictionary<int, matrix.ContainerRecord> _dataMap;
    private readonly System.Collections.Generic.List<matrix.ContainerRecord> _dataList;
    
    public TbContainers(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, matrix.ContainerRecord>(count);
        _dataList = new System.Collections.Generic.List<matrix.ContainerRecord>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            matrix.ContainerRecord _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.matrix.ContainerRecord.DeserializeContainerRecord(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, matrix.ContainerRecord> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<matrix.ContainerRecord> DataList => _dataList;

    public matrix.ContainerRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public matrix.ContainerRecord Get(int key) => _dataMap[key];
    public matrix.ContainerRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

