
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.matrix
{
public partial class TbVerticalMerged
{

     private readonly matrix.VerticalMerged _data;

     public matrix.VerticalMerged Data => _data;

    public TbVerticalMerged(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = global::cfg.matrix.VerticalMerged.DeserializeVerticalMerged(_buf[0]);  }
    }


    /// <summary>
    /// 名称
    /// </summary>
     public string Name => _data.Name;
    /// <summary>
    /// 数量
    /// </summary>
     public int Count => _data.Count;
    /// <summary>
    /// 整数列表
    /// </summary>
     public System.Collections.Generic.List<int> Nums => _data.Nums;
    /// <summary>
    /// 字符串列表
    /// </summary>
     public System.Collections.Generic.List<string> Tags => _data.Tags;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

