
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.matrix
{
public sealed partial class VerticalMerged : Luban.BeanBase
{
    public VerticalMerged(JSONNode _buf) 
    {
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
        { var __json0 = _buf["nums"]; if(!__json0.IsArray) { throw new SerializationException(); } Nums = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Nums.Add(__v0); }   }
        { var __json0 = _buf["tags"]; if(!__json0.IsArray) { throw new SerializationException(); } Tags = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Tags.Add(__v0); }   }
    }

    public static VerticalMerged DeserializeVerticalMerged(JSONNode _buf)
    {
        return new matrix.VerticalMerged(_buf);
    }

    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 整数列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> Nums;
    /// <summary>
    /// 字符串列表
    /// </summary>
    public readonly System.Collections.Generic.List<string> Tags;
   
    public const int __ID__ = 1899624495;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "count:" + Count + ","
        + "nums:" + Luban.StringUtil.CollectionToString(Nums) + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "}";
    }
}
}

