
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.test
{
public sealed partial class DemoGroup : Luban.BeanBase
{
    public DemoGroup(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["x2"].IsNumber) { throw new SerializationException(); }  X2 = _buf["x2"]; }
        X2_Ref = null;
        { if(!_buf["x4"].IsNumber) { throw new SerializationException(); }  X4 = _buf["x4"]; }
        { if(!_buf["x5"].IsObject) { throw new SerializationException(); }  X5 = global::dataTables.test.InnerGroup.DeserializeInnerGroup(_buf["x5"]);  }
    }

    public static DemoGroup DeserializeDemoGroup(JSONNode _buf)
    {
        return new test.DemoGroup(_buf);
    }

    public readonly int Id;
    public readonly int X2;
    public test.DemoGroup X2_Ref;
    public readonly int X4;
    public readonly test.InnerGroup X5;
   
    public const int __ID__ = -379263008;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        X2_Ref = tables.TbDemoGroupS.GetOrDefault(X2);
        X5?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "x2:" + X2 + ","
        + "x4:" + X4 + ","
        + "x5:" + X5 + ","
        + "}";
    }
}
}

