
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.test
{
/// <summary>
/// inline bean
/// </summary>
public sealed partial class InlineBean : Luban.BeanBase
{
    public InlineBean(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = (test.InlineQuality)_buf["quality"].AsInt; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
    }

    public static InlineBean DeserializeInlineBean(JSONNode _buf)
    {
        return new test.InlineBean(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Quality
    /// </summary>
    public readonly test.InlineQuality Quality;
    /// <summary>
    /// Name
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = -611730203;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "quality:" + Quality + ","
        + "name:" + Name + ","
        + "}";
    }
}
}

