
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace dataTables.test
{ 
    public enum InlineQuality
    {
        /// <summary>
        /// Alpha
        /// </summary>
        A = 1,
        /// <summary>
        /// Beta
        /// </summary>
        B = 2,
    }

} 

