
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.test
{
public sealed partial class InnerGroup : Luban.BeanBase
{
    public InnerGroup(JSONNode _buf) 
    {
        { if(!_buf["y1"].IsNumber) { throw new SerializationException(); }  Y1 = _buf["y1"]; }
        { if(!_buf["y3"].IsNumber) { throw new SerializationException(); }  Y3 = _buf["y3"]; }
        { if(!_buf["y4"].IsNumber) { throw new SerializationException(); }  Y4 = _buf["y4"]; }
    }

    public static InnerGroup DeserializeInnerGroup(JSONNode _buf)
    {
        return new test.InnerGroup(_buf);
    }

    public readonly int Y1;
    public readonly int Y3;
    public readonly int Y4;
   
    public const int __ID__ = -587873083;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "y1:" + Y1 + ","
        + "y3:" + Y3 + ","
        + "y4:" + Y4 + ","
        + "}";
    }
}
}

