
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.test
{
public partial class TbInlineEnum
{
    private readonly System.Collections.Generic.Dictionary<int, test.InlineBean> _dataMap;
    private readonly System.Collections.Generic.List<test.InlineBean> _dataList;
    
    public TbInlineEnum(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, test.InlineBean>(count);
        _dataList = new System.Collections.Generic.List<test.InlineBean>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            test.InlineBean _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::dataTables.test.InlineBean.DeserializeInlineBean(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, test.InlineBean> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<test.InlineBean> DataList => _dataList;

    public test.InlineBean GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public test.InlineBean Get(int key) => _dataMap[key];
    public test.InlineBean this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

