
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace dataTables.matrix
{
/// <summary>
/// inner bean
/// </summary>
public sealed partial class InnerBean : Luban.BeanBase
{
    public InnerBean(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
    }

    public static InnerBean DeserializeInnerBean(JSONNode _buf)
    {
        return new matrix.InnerBean(_buf);
    }

    public readonly int Id;
    public readonly string Name;
   
    public const int __ID__ = -699676391;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "}";
    }
}
}

