
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.matrix
{
/// <summary>
/// matrix validators
/// </summary>
public sealed partial class MatrixValidators : Luban.BeanBase
{
    public MatrixValidators(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["code"].IsNumber) { throw new SerializationException(); }  Code = _buf["code"]; }
        { if(!_buf["rangeVal"].IsNumber) { throw new SerializationException(); }  RangeVal = _buf["rangeVal"]; }
        { if(!_buf["setVal"].IsString) { throw new SerializationException(); }  SetVal = _buf["setVal"]; }
    }

    public static MatrixValidators DeserializeMatrixValidators(JSONNode _buf)
    {
        return new matrix.MatrixValidators(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Code
    /// </summary>
    public readonly int Code;
    /// <summary>
    /// RangeVal
    /// </summary>
    public readonly int RangeVal;
    /// <summary>
    /// SetVal
    /// </summary>
    public readonly string SetVal;
   
    public const int __ID__ = 1142538415;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "code:" + Code + ","
        + "rangeVal:" + RangeVal + ","
        + "setVal:" + SetVal + ","
        + "}";
    }
}
}

