
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.matrix
{
/// <summary>
/// path record
/// </summary>
public sealed partial class PathRecord : Luban.BeanBase
{
    public PathRecord(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["res"].IsString) { throw new SerializationException(); }  Res = _buf["res"]; }
    }

    public static PathRecord DeserializePathRecord(JSONNode _buf)
    {
        return new matrix.PathRecord(_buf);
    }

    public readonly int Id;
    public readonly string Res;
   
    public const int __ID__ = -218038973;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "res:" + Res + ","
        + "}";
    }
}
}

