
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace dataTables.matrix
{
/// <summary>
/// singleton config
/// </summary>
public sealed partial class SingleConfig : Luban.BeanBase
{
    public SingleConfig(JSONNode _buf) 
    {
        { if(!_buf["version"].IsNumber) { throw new SerializationException(); }  Version = _buf["version"]; }
        { if(!_buf["title"].IsString) { throw new SerializationException(); }  Title = _buf["title"]; }
    }

    public static SingleConfig DeserializeSingleConfig(JSONNode _buf)
    {
        return new matrix.SingleConfig(_buf);
    }

    public readonly int Version;
    public readonly string Title;
   
    public const int __ID__ = -46799145;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "version:" + Version + ","
        + "title:" + Title + ","
        + "}";
    }
}
}

