
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.matrix
{
public partial class TbMatrixSingleton
{

     private readonly matrix.SingleConfig _data;

     public matrix.SingleConfig Data => _data;

    public TbMatrixSingleton(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = global::dataTables.matrix.SingleConfig.DeserializeSingleConfig(_buf[0]);  }
    }


     public int Version => _data.Version;
     public string Title => _data.Title;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

