
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbAutoImport1 TbAutoImport1 {get; }
    public ai.TbBehaviorTree TbBehaviorTree {get; }
    public ai.TbBlackboard TbBlackboard {get; }
    public common.TbGlobalConfig TbGlobalConfig {get; }
    /// <summary>
    /// 道具表
    /// </summary>
    public item.TbItem TbItem {get; }
    public l10n.TbL10NDemo TbL10NDemo {get; }
    public l10n.TbPatchDemo TbPatchDemo {get; }
    public matrix.TbBasic TbBasic {get; }
    public matrix.TbContainers TbContainers {get; }
    public matrix.TbMatrixSingleton TbMatrixSingleton {get; }
    public matrix.TbMatrixList TbMatrixList {get; }
    public matrix.TbValidators TbValidators {get; }
    public matrix.TbVerticalMerged TbVerticalMerged {get; }
    public tag.TbTestTag TbTestTag {get; }
    public test.TbAutoImport2 TbAutoImport2 {get; }
    public test.TbAutoImport3 TbAutoImport3 {get; }
    public test.TbTestFormat TbTestFormat {get; }
    public test.TbCompositeJsonTable3 TbCompositeJsonTable3 {get; }
    public test.TbCompositeJsonTable1 TbCompositeJsonTable1 {get; }
    public test.TbCompositeJsonTable2 TbCompositeJsonTable2 {get; }
    public test.TbDefineFromExcel2 TbDefineFromExcel2 {get; }
    public test.TbDemoGroup TbDemoGroup {get; }
    public test.TbDemoGroup_C TbDemoGroupC {get; }
    public test.TbDemoGroup_S TbDemoGroupS {get; }
    public test.TbDemoGroup_E TbDemoGroupE {get; }
    public test.TbDemoPrimitive TbDemoPrimitive {get; }
    public test.TbDetectCsvEncoding TbDetectCsvEncoding {get; }
    public test.TbExcelFromJson TbExcelFromJson {get; }
    public test.TbExcelFromJsonMultiRow TbExcelFromJsonMultiRow {get; }
    public test.TbTestFieldVariant2 TbTestFieldVariant2 {get; }
    public test.TbFullTypes TbFullTypes {get; }
    public test.TbTestGlobal TbTestGlobal {get; }
    public test.TbInlineEnum TbInlineEnum {get; }
    public test.TbItem2 TbItem2 {get; }
    public test.TbNotIndexList TbNotIndexList {get; }
    public test.TbMultiIndexList TbMultiIndexList {get; }
    public test.TbMultiUnionIndexList TbMultiUnionIndexList {get; }
    public test.TbMinimal TbMinimal {get; }
    public test.TbDataFromMisc TbDataFromMisc {get; }
    public test.TbTestMultiColumn TbTestMultiColumn {get; }
    public test.TbMultiRowTitle TbMultiRowTitle {get; }
    public test.TbMultiRowRecord TbMultiRowRecord {get; }
    public test.TbPath TbPath {get; }
    public test.TbSingleton TbSingleton {get; }
    public test.TbTestConstAlias TbTestConstAlias {get; }
    public test.TbTestIndex TbTestIndex {get; }
    public test.TbTestMap TbTestMap {get; }
    public test.TbTestRange TbTestRange {get; }
    public test.TbTestRef TbTestRef {get; }
    public test.TbTestBeRef TbTestBeRef {get; }
    public test.TbTestBeRef2 TbTestBeRef2 {get; }
    public test.TbTestSep TbTestSep {get; }
    public test.TbTestSet TbTestSet {get; }
    public test.TbTestSize TbTestSize {get; }
    public test.TbTestString TbTestString {get; }
    public test.TbTestMapper TbTestMapper {get; }
    public test.TbTestScriptableObject TbTestScriptableObject {get; }
    public test.TbTestFieldAlias TbTestFieldAlias {get; }
    public test.TbTestFieldVariant TbTestFieldVariant {get; }
    public test.TbTestNull TbTestNull {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbAutoImport1 = new TbAutoImport1(loader("tbautoimport1"));
        TbBehaviorTree = new ai.TbBehaviorTree(loader("ai_tbbehaviortree"));
        TbBlackboard = new ai.TbBlackboard(loader("ai_tbblackboard"));
        TbGlobalConfig = new common.TbGlobalConfig(loader("common_tbglobalconfig"));
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbL10NDemo = new l10n.TbL10NDemo(loader("l10n_tbl10ndemo"));
        TbPatchDemo = new l10n.TbPatchDemo(loader("l10n_tbpatchdemo"));
        TbBasic = new matrix.TbBasic(loader("matrix_tbbasic"));
        TbContainers = new matrix.TbContainers(loader("matrix_tbcontainers"));
        TbMatrixSingleton = new matrix.TbMatrixSingleton(loader("matrix_tbmatrixsingleton"));
        TbMatrixList = new matrix.TbMatrixList(loader("matrix/nested/TbMatrixList"));
        TbValidators = new matrix.TbValidators(loader("matrix_tbvalidators"));
        TbVerticalMerged = new matrix.TbVerticalMerged(loader("matrix_tbverticalmerged"));
        TbTestTag = new tag.TbTestTag(loader("tag_tbtesttag"));
        TbAutoImport2 = new test.TbAutoImport2(loader("test_tbautoimport2"));
        TbAutoImport3 = new test.TbAutoImport3(loader("test_tbautoimport3"));
        TbTestFormat = new test.TbTestFormat(loader("test_tbtestformat"));
        TbCompositeJsonTable3 = new test.TbCompositeJsonTable3(loader("test_tbcompositejsontable3"));
        TbCompositeJsonTable1 = new test.TbCompositeJsonTable1(loader("test_tbcompositejsontable1"));
        TbCompositeJsonTable2 = new test.TbCompositeJsonTable2(loader("test_tbcompositejsontable2"));
        TbDefineFromExcel2 = new test.TbDefineFromExcel2(loader("test_tbdefinefromexcel2"));
        TbDemoGroup = new test.TbDemoGroup(loader("test_tbdemogroup"));
        TbDemoGroupC = new test.TbDemoGroup_C(loader("test_tbdemogroup_c"));
        TbDemoGroupS = new test.TbDemoGroup_S(loader("test_tbdemogroup_s"));
        TbDemoGroupE = new test.TbDemoGroup_E(loader("test_tbdemogroup_e"));
        TbDemoPrimitive = new test.TbDemoPrimitive(loader("test_tbdemoprimitive"));
        TbDetectCsvEncoding = new test.TbDetectCsvEncoding(loader("test_tbdetectcsvencoding"));
        TbExcelFromJson = new test.TbExcelFromJson(loader("test_tbexcelfromjson"));
        TbExcelFromJsonMultiRow = new test.TbExcelFromJsonMultiRow(loader("test_tbexcelfromjsonmultirow"));
        TbTestFieldVariant2 = new test.TbTestFieldVariant2(loader("test_tbtestfieldvariant2"));
        TbFullTypes = new test.TbFullTypes(loader("test_tbfulltypes"));
        TbTestGlobal = new test.TbTestGlobal(loader("test_tbtestglobal"));
        TbInlineEnum = new test.TbInlineEnum(loader("test_tbinlineenum"));
        TbItem2 = new test.TbItem2(loader("test_tbitem2"));
        TbNotIndexList = new test.TbNotIndexList(loader("test_tbnotindexlist"));
        TbMultiIndexList = new test.TbMultiIndexList(loader("test_tbmultiindexlist"));
        TbMultiUnionIndexList = new test.TbMultiUnionIndexList(loader("test_tbmultiunionindexlist"));
        TbMinimal = new test.TbMinimal(loader("test_tbminimal"));
        TbDataFromMisc = new test.TbDataFromMisc(loader("test_tbdatafrommisc"));
        TbTestMultiColumn = new test.TbTestMultiColumn(loader("test_tbtestmulticolumn"));
        TbMultiRowTitle = new test.TbMultiRowTitle(loader("test_tbmultirowtitle"));
        TbMultiRowRecord = new test.TbMultiRowRecord(loader("test_tbmultirowrecord"));
        TbPath = new test.TbPath(loader("test_tbpath"));
        TbSingleton = new test.TbSingleton(loader("test_tbsingleton"));
        TbTestConstAlias = new test.TbTestConstAlias(loader("test_tbtestconstalias"));
        TbTestIndex = new test.TbTestIndex(loader("test_tbtestindex"));
        TbTestMap = new test.TbTestMap(loader("test_tbtestmap"));
        TbTestRange = new test.TbTestRange(loader("test_tbtestrange"));
        TbTestRef = new test.TbTestRef(loader("test_tbtestref"));
        TbTestBeRef = new test.TbTestBeRef(loader("test_tbtestberef"));
        TbTestBeRef2 = new test.TbTestBeRef2(loader("test_tbtestberef2"));
        TbTestSep = new test.TbTestSep(loader("test_tbtestsep"));
        TbTestSet = new test.TbTestSet(loader("test_tbtestset"));
        TbTestSize = new test.TbTestSize(loader("test_tbtestsize"));
        TbTestString = new test.TbTestString(loader("test_tbteststring"));
        TbTestMapper = new test.TbTestMapper(loader("test_tbtestmapper"));
        TbTestScriptableObject = new test.TbTestScriptableObject(loader("test_tbtestscriptableobject"));
        TbTestFieldAlias = new test.TbTestFieldAlias(loader("test_tbtestfieldalias"));
        TbTestFieldVariant = new test.TbTestFieldVariant(loader("test_tbtestfieldvariant"));
        TbTestNull = new test.TbTestNull(loader("test_tbtestnull"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbAutoImport1.ResolveRef(this);
        TbBehaviorTree.ResolveRef(this);
        TbBlackboard.ResolveRef(this);
        TbGlobalConfig.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbL10NDemo.ResolveRef(this);
        TbPatchDemo.ResolveRef(this);
        TbBasic.ResolveRef(this);
        TbContainers.ResolveRef(this);
        TbMatrixSingleton.ResolveRef(this);
        TbMatrixList.ResolveRef(this);
        TbValidators.ResolveRef(this);
        TbVerticalMerged.ResolveRef(this);
        TbTestTag.ResolveRef(this);
        TbAutoImport2.ResolveRef(this);
        TbAutoImport3.ResolveRef(this);
        TbTestFormat.ResolveRef(this);
        TbCompositeJsonTable3.ResolveRef(this);
        TbCompositeJsonTable1.ResolveRef(this);
        TbCompositeJsonTable2.ResolveRef(this);
        TbDefineFromExcel2.ResolveRef(this);
        TbDemoGroup.ResolveRef(this);
        TbDemoGroupC.ResolveRef(this);
        TbDemoGroupS.ResolveRef(this);
        TbDemoGroupE.ResolveRef(this);
        TbDemoPrimitive.ResolveRef(this);
        TbDetectCsvEncoding.ResolveRef(this);
        TbExcelFromJson.ResolveRef(this);
        TbExcelFromJsonMultiRow.ResolveRef(this);
        TbTestFieldVariant2.ResolveRef(this);
        TbFullTypes.ResolveRef(this);
        TbTestGlobal.ResolveRef(this);
        TbInlineEnum.ResolveRef(this);
        TbItem2.ResolveRef(this);
        TbNotIndexList.ResolveRef(this);
        TbMultiIndexList.ResolveRef(this);
        TbMultiUnionIndexList.ResolveRef(this);
        TbMinimal.ResolveRef(this);
        TbDataFromMisc.ResolveRef(this);
        TbTestMultiColumn.ResolveRef(this);
        TbMultiRowTitle.ResolveRef(this);
        TbMultiRowRecord.ResolveRef(this);
        TbPath.ResolveRef(this);
        TbSingleton.ResolveRef(this);
        TbTestConstAlias.ResolveRef(this);
        TbTestIndex.ResolveRef(this);
        TbTestMap.ResolveRef(this);
        TbTestRange.ResolveRef(this);
        TbTestRef.ResolveRef(this);
        TbTestBeRef.ResolveRef(this);
        TbTestBeRef2.ResolveRef(this);
        TbTestSep.ResolveRef(this);
        TbTestSet.ResolveRef(this);
        TbTestSize.ResolveRef(this);
        TbTestString.ResolveRef(this);
        TbTestMapper.ResolveRef(this);
        TbTestScriptableObject.ResolveRef(this);
        TbTestFieldAlias.ResolveRef(this);
        TbTestFieldVariant.ResolveRef(this);
        TbTestNull.ResolveRef(this);
    }
}

}

