
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.matrix
{
/// <summary>
/// basic record
/// </summary>
public sealed partial class BasicRecord : Luban.BeanBase
{
    public BasicRecord(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = (matrix.EQuality)_buf["quality"].AsInt; }
        { if(!_buf["textKey"].IsString) { throw new SerializationException(); }  TextKey = _buf["textKey"]; }
        { if(!_buf["res"].IsString) { throw new SerializationException(); }  Res = _buf["res"]; }
        { if(!_buf["enabled"].IsBoolean) { throw new SerializationException(); }  Enabled = _buf["enabled"]; }
        { if(!_buf["score"].IsNumber) { throw new SerializationException(); }  Score = _buf["score"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
        { if(!_buf["created"].IsNumber) { throw new SerializationException(); }  Created = _buf["created"]; }
        { var _j = _buf["optName"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsString) { throw new SerializationException(); }  OptName = _j; } } else { OptName = null; } }
        { if(!_buf["notDefault"].IsNumber) { throw new SerializationException(); }  NotDefault = _buf["notDefault"]; }
    }

    public static BasicRecord DeserializeBasicRecord(JSONNode _buf)
    {
        return new matrix.BasicRecord(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly matrix.EQuality Quality;
    public readonly string TextKey;
    public readonly string Res;
    public readonly bool Enabled;
    public readonly float Score;
    public readonly long Count;
    public readonly long Created;
    public readonly string OptName;
    public readonly int NotDefault;
   
    public const int __ID__ = 2133733202;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "textKey:" + TextKey + ","
        + "res:" + Res + ","
        + "enabled:" + Enabled + ","
        + "score:" + Score + ","
        + "count:" + Count + ","
        + "created:" + Created + ","
        + "optName:" + OptName + ","
        + "notDefault:" + NotDefault + ","
        + "}";
    }
}
}

