
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.matrix
{
/// <summary>
/// container record
/// </summary>
public sealed partial class ContainerRecord : Luban.BeanBase
{
    public ContainerRecord(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["nums"]; if(!__json0.IsArray) { throw new SerializationException(); } Nums = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Nums.Add(__v0); }   }
        { var __json0 = _buf["tags"]; if(!__json0.IsArray) { throw new SerializationException(); } Tags = new System.Collections.Generic.HashSet<string>(/*__json0.Count*/); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Tags.Add(__v0); }   }
        { var __json0 = _buf["props"]; if(!__json0.IsArray) { throw new SerializationException(); } Props = new System.Collections.Generic.Dictionary<int, string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } string _v0;  { if(!__e0[1].IsString) { throw new SerializationException(); }  _v0 = __e0[1]; }  Props.Add(_k0, _v0); }   }
        { var __json0 = _buf["innerList"]; if(!__json0.IsArray) { throw new SerializationException(); } InnerList = new System.Collections.Generic.List<matrix.InnerBean>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { matrix.InnerBean __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::dataTables.matrix.InnerBean.DeserializeInnerBean(__e0);  }  InnerList.Add(__v0); }   }
    }

    public static ContainerRecord DeserializeContainerRecord(JSONNode _buf)
    {
        return new matrix.ContainerRecord(_buf);
    }

    public readonly int Id;
    public readonly System.Collections.Generic.List<int> Nums;
    public readonly System.Collections.Generic.HashSet<string> Tags;
    public readonly System.Collections.Generic.Dictionary<int, string> Props;
    public readonly System.Collections.Generic.List<matrix.InnerBean> InnerList;
   
    public const int __ID__ = 1784679397;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in InnerList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nums:" + Luban.StringUtil.CollectionToString(Nums) + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "props:" + Luban.StringUtil.CollectionToString(Props) + ","
        + "innerList:" + Luban.StringUtil.CollectionToString(InnerList) + ","
        + "}";
    }
}
}

