
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace dataTables.matrix
{
public partial class TbMatrixList
{
    private readonly System.Collections.Generic.List<matrix.ListRecord> _dataList;


    public TbMatrixList(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<matrix.ListRecord>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            matrix.ListRecord _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::dataTables.matrix.ListRecord.DeserializeListRecord(_ele);  }
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<matrix.ListRecord> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

